<?php
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\RoleInterface;

/**
 * Implements hook_help().
 */
function riddle_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.riddle':
      return t(
        '
        <h2>Riddle Editor for Drupal.</h2>
        <h3>Instructions</h3>
        <p>Goto Riddle.com and get an auth token</p>
      '
      );
  }
}

